name: Simple pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: '16'
      - name: Clean 
        run: npm ci
      - name: Install dependencies
        run: npm install
      - name: Check style 
        run: npm run-script eslint
      - name: Build 
        run: npm run build
      - name: Test
        run: npm run test
      - name: e2e-tests
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          start: npm start-prod
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Deploy
      # deploy only on push / pull to main 
        if: ${{ github.event_name == 'push' }}
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message),'#SKIP') }}
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
        
