name: Simple pipeline

on:
  push:
    branches: [main]

jobs:
  render_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with: 
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Check style 
        run: npm run-script eslint
      - name: Build 
        run: npm run build
      - name: Test
        run: npm run test
      - name: Trigger deployment
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
